name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build backend
      run: |
        cd converter-backend
        ./mvnw clean install

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build frontend
      run: |
        cd converter-frontend/UMLtoOpenAPISpec
        npm install
        npm run build

    - name: Start Prism mock server
      run: docker-compose up -d

    - name: Wait for Prism mock server to be healthy
      run: |
        echo "Waiting for Prism mock server to be healthy..."
        for i in {1..10}; do
          if docker-compose ps | grep prism | grep "healthy"; then
            echo "Prism mock server is healthy."
            break
          else
            echo "Waiting for Prism mock server..."
            sleep 10
          fi
        done

    - name: Run backend tests
      run: |
        cd converter-backend
        ./mvnw test

    - name: Run frontend tests
      run: |
        cd converter-frontend/UMLtoOpenAPISpec
        npm run test

    - name: Run API tests against mock server
      run: |
        npm install -g newman
        newman run tests/api-tests.postman_collection.json --env-var baseUrl=http://localhost:4011
