name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set executable permission for mvnw
      run: chmod +x converter-backend/mvnw

    - name: Build backend
      run: |
        cd converter-backend
        ./mvnw clean install

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Build frontend
      run: |
        cd converter-frontend/UMLtoOpenAPISpec
        npm install
        npm run build

  test-backend:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set executable permission for mvnw
      run: chmod +x converter-backend/mvnw

    - name: Run backend tests
      run: |
        cd converter-backend
        ./mvnw test

  test-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
      working-directory: converter-frontend/UMLtoOpenAPISpec

    - name: Run frontend tests
      run: npm test
      working-directory: converter-frontend/UMLtoOpenAPISpec

  deploy:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set executable permission for mvnw
      run: chmod +x converter-backend/mvnw

    - name: Start backend and frontend services
      run: docker-compose up -d converter-backend converter-frontend

    - name: Stop Docker Compose services
      run: docker-compose down
