name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set executable permission for mvnw
      run: chmod +x converter-backend/mvnw

    - name: Build backend
      run: |
        cd converter-backend
        ./mvnw clean install

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Build frontend
      run: |
        cd converter-frontend/UMLtoOpenAPISpec
        npm install
        npm run build

    - name: Start backend and frontend services
      run: docker-compose up -d converter-backend converter-frontend

    - name: Run backend tests
      run: |
        cd converter-backend
        ./mvnw test

    - name: Stop Docker Compose services
      run: docker-compose down
