name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      prism:
        image: stoplight/prism:4
        ports:
          - 4010:4010
        options: >-
          --health-cmd="curl --fail http://localhost:4010/ || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          PRISM_MOCK: '1'
          PRISM_FILE: /data/export.yml
        volumes:
          - ./data:/data

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build backend
      run: |
        cd converter-backend
        ./mvnw clean install

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build frontend
      run: |
        cd converter-frontend/UMLtoOpenAPISpec
        npm install
        npm run build

    - name: Start Prism mock server
      run: docker-compose up -d

    - name: Wait for Prism mock server
      run: sleep 20s

    - name: Run backend tests
      run: |
        cd converter-backend
        ./mvnw test

    - name: Run frontend tests
      run: |
        cd converter-frontend/UMLtoOpenAPISpec
        npm run test

    - name: Run API tests against mock server
      run: |
        npm install -g newman
        newman run tests/api-tests.postman_collection.json
